### ISSUE TITLE
decimal precision

### ISSUE THREAD

**Issue by Boyettw** [amzn/ion-c#111]
2000000000d100 roundtrips as 2.000000000d+109 within the event suite.
This is destructive.

**Comment by tgregg** [comment]
http://amzn.github.io/ion-docs/docs/decimal.html

Before converting to the decimal data model tuple (which is used to determine equivalence), the decimals are normalized according to the following:

> If the decimal-part included a decimal point the exponent is then reduced by the count of digits following the decimal point (which may be zero) and the decimal point is removed.

So, nothing happens to 2000000000d100, but 2.000000000d+109 is converted to 2000000000d100. Therefore, they are equivalent representations.
