### ISSUE TITLE
Consider alternatives to docopt

### ISSUE THREAD

**Issue by tgregg** [amzn/ion-c#133]
Docopt, which is used by the CLI for argument parsing, has strict toolchain requirements (see #131), has problems on Windows (see #95), and produces compiler warnings that point to possible memory leaks.

Some time should be spent to see if it's possible to quickly patch the docopt submodule to resolve these issues. Otherwise, consider replacing docopt with ionizer's argument parsing logic.

**Comment by therapon** [comment]
I accidentally stumbled on this today [ArgTable](https://github.com/argtable/argtable3). Seems to be used for Unix, Windows and Mac.
