### ISSUE TITLE
Closing binary writer does not flush output stream

### ISSUE THREAD

**Issue by JohnMcPMS** [amzn/ion-c#140]
I found this in ionizer; using -a works fine to output a file, but -b doesn't produce any output.  Upon debugging, I found that _ion_writer_text_close flushes the output stream, whereas _ion_writer_binary_close doesn't.  It does flush from the internal buffer to the output stream.

I'm not sure whether the intention is that the writer close or the stream close flushes the stream, but the behavior is inconsistent between the text and binary writers in either case.

It also looks like the stream is never actually closed in ionizer_writer_close_fstream.

**Comment by raganhan** [comment]
Thanks for reporting this bug

Here is an easy way to reproduce this issue: 
`$ echo "{a: 1}" | ./ionizer -b`

**Comment by raganhan** [comment]
Both writers should the stream on close as [ion_writer_close](https://github.com/amzn/ion-c/blob/master/ionc/include/ionc/ion_writer.h#L276) finishes the writer which flushes any pending bytes.
