### ISSUE TITLE
ion-c reader should stop once it detects errors.

### ISSUE THREAD

**Issue by cheqianh** [amzn/ion-c#204]
Test file: intWithTerminatingColon

ion-c should stop reading once it detects errors rather than read half of data.

**Comment by tgregg** [comment]
More specifically for this file: if the numeric value does not end with a valid terminating character, an error should be raised before returning the numeric value.

**Comment by cheqianh** [comment]
### Description:
**Our logic to read a numeric value before is:** 
1. Read digit char until reaching a terminating char or invalid char, return numeric value. 
2. After step 1 and the function calls read_next again, Raise an error for the invalid char if possible.

**After changing:**
1. Read digit char until reaching a terminating char or invalid char, 
2. Before we return the numeric value, check the last char we read. If it is invalid, raise an error.

&nbsp;

### Output:
<img width="796" alt="Screen Shot 2020-10-09 at 3 11 53 PM" src="https://user-images.githubusercontent.com/67451029/95635635-c8073680-0a41-11eb-98e1-c4eeb171cf39.png">

&nbsp;
### Test:
I used build/release/test/all_tests to test. 

Before: 
<img width="535" alt="Screen Shot 2020-10-09 at 2 42 29 PM" src="https://user-images.githubusercontent.com/67451029/95633964-ab68ff80-0a3d-11eb-9a6e-8ad5a3be535c.png">

After:
<img width="581" alt="Screen Shot 2020-10-09 at 2 46 30 PM" src="https://user-images.githubusercontent.com/67451029/95634226-3c3fdb00-0a3e-11eb-984c-d82e86c8fac3.png">

I found that `IonTextDecimal.FailsEarlyOnInvalidDecimal` didn't pass after changing.

Looking in to `IonTextDecimal.FailsEarlyOnInvalidDecimal`: 
![Screen Shot 2020-10-09 at 2 48 24 PM](https://user-images.githubusercontent.com/67451029/95634336-845efd80-0a3e-11eb-8222-6522abc625cc.png)

Before, we read the decimal value successfully and  raise an error when we trying to read this invalid decimal value from the reader. After this change, the reader finds the invalid decimal value immediately when reader reads the next value.

So I modified this test case a little bit (Change ION_ASSERT_OK to ION_ASSERT_FAIL for ion_reader_next()): 
![Screen Shot 2020-10-09 at 3 09 08 PM](https://user-images.githubusercontent.com/67451029/95635487-647d0900-0a41-11eb-8d85-54b1258294a8.png)

After that I run the all_tests again and it passed:
<img width="612" alt="Screen Shot 2020-10-09 at 3 09 40 PM" src="https://user-images.githubusercontent.com/67451029/95635517-765eac00-0a41-11eb-8aaf-785fc1fb5d8d.png">

**Comment by cheqianh** [comment]
### Description:
**Our logic to read a numeric value before is:** 
1. Read numeric value until reaching a terminating char or invalid char, return numeric value. 
2. After step 1 and the function calls read_next again, Raise an error for the invalid char if possible.

**After changing:**
1. Read numeric value until reaching a terminating char or invalid char, 
2. Before we return the numeric value, check the last char we read. If it is invalid, raise an error.

&nbsp;

### Output:
<img width="796" alt="Screen Shot 2020-10-09 at 3 11 53 PM" src="https://user-images.githubusercontent.com/67451029/95635635-c8073680-0a41-11eb-98e1-c4eeb171cf39.png">

&nbsp;
### Test:
I used build/release/test/all_tests to test. 

Before: 
<img width="535" alt="Screen Shot 2020-10-09 at 2 42 29 PM" src="https://user-images.githubusercontent.com/67451029/95633964-ab68ff80-0a3d-11eb-9a6e-8ad5a3be535c.png">

After:
<img width="581" alt="Screen Shot 2020-10-09 at 2 46 30 PM" src="https://user-images.githubusercontent.com/67451029/95634226-3c3fdb00-0a3e-11eb-984c-d82e86c8fac3.png">

I found that `IonTextDecimal.FailsEarlyOnInvalidDecimal` didn't pass after changing.

Looking in to `IonTextDecimal.FailsEarlyOnInvalidDecimal`: 
![Screen Shot 2020-10-09 at 2 48 24 PM](https://user-images.githubusercontent.com/67451029/95634336-845efd80-0a3e-11eb-8222-6522abc625cc.png)

Before, we read the decimal value successfully and  raise an error when we trying to read this invalid decimal value from the reader. After this change, the reader finds the invalid decimal value immediately when reader reads the next value.

So I modified this test case a little bit (Change ION_ASSERT_OK to ION_ASSERT_FAIL for ion_reader_next()): 
![Screen Shot 2020-10-09 at 3 09 08 PM](https://user-images.githubusercontent.com/67451029/95635487-647d0900-0a41-11eb-8d85-54b1258294a8.png)

After that I run the all_tests again and it passed:
<img width="612" alt="Screen Shot 2020-10-09 at 3 09 40 PM" src="https://user-images.githubusercontent.com/67451029/95635517-765eac00-0a41-11eb-8aaf-785fc1fb5d8d.png">
