### ISSUE TITLE
will you create ion-hash-c?

### ISSUE THREAD

**Issue by wukakuki** [amzn/ion-c#208]
will you create ion-hash-c? ion-cpp and ion-hash-cpp?

**Comment by zslayton** [comment]
We would like to provide a native implementation of `ion-hash` eventually but have not scheduled this work in the near term.

In the meantime, [the `ion-hash` specification](https://amzn.github.io/ion-hash/docs/spec.html) is publicly available should you (or anyone else) wish to begin working on an implementation.

**Comment by wukakuki** [comment]
https://github.com/wukakuki/ion-hash-cpp 
I created it.
