### ISSUE TITLE
Ion binary crashes with floating point exception

### ISSUE THREAD

**Issue by docfate111** [amzn/ion-c#221]
Running build-release.sh to install creates ion and ionizer.
Going into ion-c/build/release/tools/cli

Running 
```
ion process [filename]
```

cause floating point exception for some inputs such as 
```
[[1, -12D516753754312305], [-629107941, 255.0], []]
```
or 
```
[[1, -12.516753754312305], [-6D9107941, 255.0], []]
```

**Comment by tgregg** [comment]
This error is triggered by the following numbers.

`-12D516753754312305`
`-6D9107941`

This seems to be because the `decNumber` library does not support exponents this large. It should fail more gracefully than with `SIGFPE`, though.

Do you have a use case for decimals with exponents this large?

**Comment by docfate111** [comment]
No I am just practicing fuzzing stuff/looking for security issues.

**Comment by tgregg** [comment]
Thanks for the report, @docfate111 . I'm going to reopen this so we can raise a more graceful error.

**Comment by m6w6** [comment]
Is there any reason `decContext.traps` is actually set?
```diff
diff --git a/tools/events/ion_event_util.cpp b/tools/events/ion_event_util.cpp
index 5a26a5d..5f61843 100644
--- a/tools/events/ion_event_util.cpp
+++ b/tools/events/ion_event_util.cpp
@@ -22,7 +22,7 @@ decContext g_IonEventDecimalContext = {
         DEC_MAX_MATH,                   // max exponent
         -DEC_MAX_MATH,                  // min exponent
         DEC_ROUND_HALF_EVEN,            // rounding mode
-        DEC_Errors,                     // trap conditions
+        0,                              // trap conditions
         0,                              // status flags
         0                               // apply exponent clamp?
 };
```
```ion
{
  error_type: READ,
  message: "/home/mike/src/ion-c/tools/events/ion_event_stream.cpp:364 : IERR_NUMERIC_OVERFLOW",
  location: "sigfpe.ion"
}
```
