### ISSUE TITLE
Compiler Warning: extra tokens at end of #ifdef directive

### ISSUE THREAD

**Issue by kobalicek** [amzn/ion-c#230]
The library uses the following construct:

```
 #ifdef __STDC_VERSION__ >= 201112L
```

which produces the mentioned warning. I think it should use the following instead:

```
 #if __STDC_VERSION__ >= 201112L
```

**Comment by jobarr-amzn** [comment]
It looks like you're right- `#ifdef __STDC_VERSION__ >= 201112L` *might* work for some compilers but shouldn't by spec, whereas what C specifications I could find (C99, C0X, and the new C standard) all agree in 6.10.1 that:
>After all replacements due to macro expansion and the defined unary operator have been performed, all remaining identifiers are replaced with the pp-number `0`, and then each preprocessing token is converted into a token.

**Comment by jobarr-amzn** [comment]
Thanks for the bug report!

**Comment by kobalicek** [comment]
Just a note - I'm not sure whether __STDC_VERSION__ is defined in C++ mode. Maybe it would need a bit more elaborate #ifdefs to make it working across all possible compilers in both C and C++ compilation modes.
