### ISSUE TITLE
I have created a cpp wrapper for ion c and a cpp implement for ion hash. hope it will help somebody.

### ISSUE THREAD

**Issue by wukakuki** [amzn/ion-c#253]
I have created a cpp wrapper for ion c and a cpp implement for ion hash. hope it will help somebody.

https://github.com/wukakuki/ion-hash-cpp

**Comment by Xpakeb13Git** [comment]
Great work! Keep going!

**Comment by popematt** [comment]
Hi @wukakuki, thanks for telling us about your project.

Once your project gets further along, if you would like your project to be considered for addition to the list of community supported Ion projects, please open a PR (like [this one](https://github.com/amzn/ion-docs/pull/154)) in the ion-docs repository.
