### ISSUE TITLE
Ion stream is not getting closed when using a binary writer.

### ISSUE THREAD

**Issue by wibloe** [amzn/ion-c#256]
We are using a binary writer created by ion_writer_open_buffer(). When the data is written, the writer is closed. While doing the open, write(s) and close repeatedly, we've noticed increasing memory usage. The memory leak seems to be caused by the _value_stream in the _ion_binary_writer structure  not getting closed when the writer is closed.  Adding the following before closing the writer fixed the problem:

 rc = ion_stream_close(writer->_typed_writer.binary._value_stream);

Also, is it possible to reuse the writer created with ion_writer_open_buffer() so could I skip the closing and creating a new writer? 

Thanks!

**Comment by cheqianh** [comment]
Thanks for reporting this, I created a [PR](https://github.com/amzn/ion-c/pull/257) fixing this.

For the second question. I looked into ion-c writer APIs but didn't find an obvious way to reuse the writer. I'll discuss this with engineers having more experience on the ion-c and update here if there is a way to reuse the writer.

**Comment by cheqianh** [comment]
Fix https://github.com/amzn/ion-c/pull/257 is merged.
