### ISSUE TITLE
Why are global IVM symbol BYTE/ION_STRING named VTM?

### ISSUE THREAD

**Issue by m6w6** [amzn/ion-c#266]
Is this intentional or a legacy leftover?

**Comment by m6w6** [comment]
While we're at it, `ION_SYS_SYMBOL_ION_SYMBOL_TABLE` is an outlier, too.

**Comment by tgregg** [comment]
> Is this intentional or a legacy leftover?

It's a legacy leftover. I'm not sure about the origin of the VTM acronym, as it's not used in any of our current documentation that I'm aware of.

> While we're at it, ION_SYS_SYMBOL_ION_SYMBOL_TABLE is an outlier, too.

Can you clarify your question about this one?

**Comment by m6w6** [comment]
> > While we're at it, ION_SYS_SYMBOL_ION_SYMBOL_TABLE is an outlier, too.
> 
> Can you clarify your question about this one?

Sorry, everything else is named `ION_SYS_(SYMBOL|SID|STRLEN)_ ...`, i.e. I would have expected it to be named `ION_SYS_SYMBOL_SYMBOL_TABLE`, but it has an additional `ION` in between and is named `ION_SYS_SYMBOL_ION_SYMBOL_TABLE`.

Or maybe `ION_SYS_(.*)_SHARED_SYMBOL_TABLE` should rather have `ION` added because the text starts with `$ion`.

Anyway, I guess debating naming legacy doesn't lead to anywhere.
